name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Upgrade npm to latest version
        run: npm install -g npm@latest

      - name: Install dependencies
        run: |
          npm install
          npm audit fix  # automatyczna naprawa luk bezpieczeństwa

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Start server
        run: npm start &
        env:
          CI: true

      - name: Wait for server to start
        run: sleep 10

      - name: Check server is running
        run: curl -f http://localhost:3000 || (echo "Server did not start correctly" && exit 1)
